### ISSUE TITLE
[Bug]: hardware mouse and touch controls

### ISSUE THREAD

**Issue by xodiosx** [jiaxinchen-max/termux-app#2]
### Problem description

First it's hardware mouse (external mouse) not captured by x11 when moving the pointer around the screen. Because of the touch controls from winlator has it's own mouse events .
Second the soft keyboard wont open bug because of the buttons events i guess so it would work better if it opens by volume keys instead.

### Steps to reproduce the behavior.

Plug in external mouse open app start any desktop environment, mouse pointer not moving with the hardware mouse.
Note; Older versions without winlator touch controls doesn't have the mouse bugs.

### What is the expected behavior?

External Mouse and keyboard working as normaly as in x11 desktop environment 

### System information

* Termux application version:118
* Android OS version:10
* Device model: SM-G960U

**Comment by jiaxinchen-max** [comment]
physics mouse or keyboard not adapt yet.  adapted in future. 
soft keyboard will open from setting view->open soft keyboard option instead of back key
back key is used for unlock view slider.

**Comment by xodiosx** [comment]
Hopefully it gets supported soon,, because the app in general is brilliant idea,, good luck master

**Comment by jiaxinchen-max** [comment]
> Hopefully it gets supported soon,, because the app in general is brilliant idea,, good luck master

hardware mouse has been supported

**Comment by xodiosx** [comment]
Ok sorry for late reply,, I'll check it out thanks master,,

**Comment by xodiosx** [comment]
Its working thanks ♥️
