### ISSUE TITLE
[Bug]: CANNOT LINK EXECUTABLE mpv : cannot locate symbol eglDestroySyncKHR referenced by /system/lib64/libgui.so ...

### ISSUE THREAD

**Issue by xodiosx** [jiaxinchen-max/termux-app#3]
### Problem description

Mpv package working fine in the previous version of the app but in the New update it shows the error 
CANNOT LINK EXECUTABLE mpv : cannot locate symbol eglDestroySyncKHR referenced by /system/lib64/libgui.so ...
I think its because of the bootstrap package or something,,

### Steps to reproduce the behavior.

1 Pkg Install mpv 
2 run mpv any.mp3 file 
3 shows the error

### What is the expected behavior?

Playing the mp3 file in command screen
Like the older version

### System information

* Termux application version:118
* Android OS version:10
* Device model: Samsung Galaxy S9

**Comment by xodiosx** [comment]
Its not libs from apk not even bootstrap.so because i tried troubleshooting libs and same issue with mpv so it's something else inside New update app ,,

**Comment by jiaxinchen-max** [comment]
android5 is too old and can not be comptitable with current app's display tech, for android5, you should download apt-5 apk instead of apt-7 apk

**Comment by xodiosx** [comment]
Its about the sound its not working as will in the android 5 version but it works if no virgl server is opened ,,??

**Comment by xodiosx** [comment]
Tried to build again but same error

**Comment by jiaxinchen-max** [comment]
it not matter about termux self, but termux package, more and more feature was deprecated in termux package.
with my modified termux, it supports android7 and above
give up android 5, too old as it is.

**Comment by xodiosx** [comment]
Understood it's termux issues,, would be great if there's android 7 universal apk
